import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from './components/Hero'
import Hours from './components/Hours'
import ExplainerSection from './components/ExplainerSection'
import Specials from './components/Specials'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SunnySide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
<Hero/>
<ExplainerSection/>
<Specials/>

<Hours/>
<Footer/>
     </div>
    </>
  )
}
